name: Build Image

on:
  pull_request:
    branches:
      - main
    paths:
      # '*' matches any character except '/'
      - 'image/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build Imag
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-agent-docker
          docker build -t ${IMAGE_NAME} -f Dockerfile.jdk8 .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:jdk8"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"

