name: Build and Push Image

on:
  push:
    branches:
      - main
    paths:
      # '*' matches any character except '/'
      - 'images/*'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets. DOCKER_HUB_USERNAME }} 
          DOCKER_HUB_PASSWORD: ${{ secrets. DOCKER_HUB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin
          
      - name: Build & Push Image -- 
        run: |
          cd images
          IMAGE_NAME=ringcentral/int-agent-docker
          docker build -t ${IMAGE_NAME} -f Dockerfile.jdk8 .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:jdk8"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:jdk8"
          docker push "${IMAGE_NAME}:latest"
